apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "notes.labels" . | nindent 4 }}
data:
  APP_NAME: {{ .Values.app.name | quote }}
  ENVIRONMENT: {{ .Values.app.environment | quote }}
  index.html: |
    <!doctype html>
    <html><head><title>{{ .Values.app.banner }}</title></head>
    <body style="font-family:sans-serif;margin:3rem">
      <h1>{{ .Values.app.banner }}</h1>
      <p>environment: <b>{{ .Values.app.environment }}</b> &middot; release: <b>{{ .Release.Name }}</b> &middot; revision: <b>{{ .Release.Revision }}</b></p>
      <p>image: {{ .Values.image.repository }}:{{ .Values.image.tag }} &middot; replicas: {{ .Values.replicaCount }}</p>
    </body></html>
