apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
  labels:
    {{- include "notes.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "notes.selector" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "notes.selector" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
              name: http
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
          volumeMounts:
            - name: page
              mountPath: /usr/share/nginx/html
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: http
      volumes:
        - name: page
          configMap:
            name: {{ .Release.Name }}-config
            items:
              - key: index.html
                path: index.html
